// <auto-generated />
namespace SONRCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StandingOrder2ndTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandingOrder2ndTry));
        
        string IMigrationMetadata.Id
        {
            get { return "201602142030113_StandingOrder2ndTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
