// <auto-generated />
namespace SONRCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StandingOrderTypeCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandingOrderTypeCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201602142027321_StandingOrderTypeCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
